/************************

Populate the table student

*************************/

INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('TSO HUI LIN', 'tsohuilin1989@msn.com', '2021-08-01', 'Faculty of Science', 'Physics', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('GERALDINE LEE', 'glee@msn.com', '2021-08-01', 'School of Computing', 'IS', '2024-07-31');
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ADELINE WONG', 'awong007@msn.com', '2021-08-01', 'School of Computing', 'CS', '2024-07-31');
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('TANG CHEE YONG', 'tcy@hotmail.com', '2021-08-01', 'School of Computing', 'IS', '2024-07-31');
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('DING GEK PING', 'dinggekping1991@msn.com', '2021-08-01', 'Faculty of Science', 'Physics', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('LIU SHAOJUN', 'liushaojun2010@msn.com', '2021-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('NI HANRAN', 'nihanran1989@msn.com', '2021-08-01', 'Faculty of Science', 'Physics', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ANUPAMA ANGHAN', 'anupamaanghan2010@yahoo.com', '2023-08-01', 'Faculty of Engineering', 'CE', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('DENNIS BECKHAM', 'dennisbeckham1989@msn.com', '2024-08-01', 'School of Computing', 'IS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ZHANG ZHUO', 'zhangzhuo1989@hotmail.com', '2021-08-01', 'Faculty of Science', 'Math', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('LIU QIAN', 'liuqian1991@yahoo.com', '2023-08-01', 'Faculty of Arts and Social Science', 'Geography', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ZHANG YINGBO', 'zhangyingbo1989@msn.com', '2024-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('CHIA YEU ARNG', 'chiayeuarng1991@hotmail.com', '2022-08-01', 'Faculty of Science', 'Math', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ZENG YIHUI', 'zengyihui2010@yahoo.com', '2022-08-01', 'Faculty of Arts and Social Science', 'History', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('FENG MENG', 'fengmeng1990@gmail.com', '2021-08-01', 'Faculty of Science', 'Biology', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ZHANG HAN', 'zhanghan1989@hotmail.com', '2022-08-01', 'Faculty of Arts and Social Science', 'History', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('LIU DANNI', 'liudanni1991@yahoo.com', '2024-08-01', 'Faculty of Engineering', 'ME', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('SOH JIE FENG', 'sohjiefeng1991@msn.com', '2024-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('XIE XIN', 'xiexin2011@gmail.com', '2021-08-01', 'Faculty of Science', 'Chemistry', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('GOH HUI YING', 'gohhuiying1989@gmail.com', '2022-08-01', 'Faculty of Science', 'Biology', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('FANG HAN', 'fanghan2011@hotmail.com', '2022-08-01', 'Faculty of Arts and Social Science', 'Geography', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('TAY WEI GUO', 'tayweiguo1989@msn.com', '2024-08-01', 'Faculty of Engineering', 'CE', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ONG KAH HONG', 'ongkahhong1991@gmail.com', '2022-08-01', 'Faculty of Science', 'Math', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('PENG JIAYUAN', 'pengjiayuan2011@hotmail.com', '2022-08-01', 'Faculty of Science', 'Biology', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('HUANG ZHANPENG', 'huangzhanpeng1992@msn.com', '2024-08-01', 'Faculty of Arts and Social Science', 'Geography', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('NGOO GEK PING', 'ngoogekping1990@hotmail.com', '2023-08-01', 'Faculty of Science', 'Biology', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('GE YUWEI', 'geyuwei1992@hotmail.com', '2023-08-01', 'Faculty of Science', 'Physics', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('HUANG WENXIN', 'huangwenxin2010@msn.com', '2022-08-01', 'Faculty of Science', 'Math', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('WANG NA', 'wangna1990@yahoo.com', '2024-08-01', 'Faculty of Engineering', 'EE', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('HUANG QI', 'huangqi1990@msn.com', '2024-08-01', 'School of Computing', 'IS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('HUANG RAN', 'huangran1991@yahoo.com', '2021-08-01', 'Faculty of Science', 'Biology', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('GOH ENG CHYE', 'gohengchye1992@msn.com', '2021-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('LIU ZHANPENG', 'liuzhanpeng2011@msn.com', '2021-08-01', 'Faculty of Science', 'Chemistry', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('DING KUAN CHONG', 'dingkuanchong2010@msn.com', '2022-08-01', 'Faculty of Engineering', 'CE', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ZHENG ZHEMIN', 'zhengzhemin1991@yahoo.com', '2022-08-01', 'Faculty of Arts and Social Science', 'History', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('CHOY WEI XIANG', 'choyweixiang2011@gmail.com', '2022-08-01', 'Faculty of Arts and Social Science', 'Geography', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ZHOU HUICHAN', 'zhouhuichan1990@msn.com', '2022-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('NG ANH QUANG', 'nganhquang1991@yahoo.com', '2023-08-01', 'Faculty of Engineering', 'ME', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('TAN CHENG HAN', 'tanchenghan1990@msn.com', '2021-08-01', 'Faculty of Science', 'Physics', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('DING YANG', 'dingyang1989@gmail.com', '2024-08-01', 'Faculty of Arts and Social Science', 'History', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ZHANG HONG', 'zhanghong2011@msn.com', '2024-08-01', 'School of Computing', 'IS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('XU HUAJUN', 'xuhuajun1990@msn.com', '2024-08-01', 'School of Computing', 'IS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('SOMESH ANEJA', 'someshaneja2011@yahoo.com', '2021-08-01', 'Faculty of Engineering', 'EE', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('LIU YIHUI', 'liuyihui1990@hotmail.com', '2022-08-01', 'Faculty of Science', 'Biology', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ZHU CHANG', 'zhuchang2010@gmail.com', '2023-08-01', 'Faculty of Arts and Social Science', 'History', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ZHENG XI', 'zhengxi1990@yahoo.com', '2024-08-01', 'School of Computing', 'IS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('YEO JIA HAO', 'yeojiahao1989@yahoo.com', '2024-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ANNIE CHAPMAN', 'anniechapman1991@yahoo.com', '2022-08-01', 'Faculty of Arts and Social Science', 'Language', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('JERRY BROWN', 'jerrybrown2010@gmail.com', '2024-08-01', 'Faculty of Arts and Social Science', 'Economics', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('HENRY HUNT', 'henryhunt1992@yahoo.com', '2024-08-01', 'Faculty of Arts and Social Science', 'Geography', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('LIU JUN', 'liujun1992@msn.com', '2024-08-01', 'Faculty of Engineering', 'EE', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ZHANG ZHANPENG', 'zhangzhanpeng1992@hotmail.com', '2021-08-01', 'Faculty of Science', 'Math', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('DAVID CHAPMAN', 'davidchapman1989@msn.com', '2022-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('DENNIS PALMER', 'dennispalmer1992@yahoo.com', '2024-08-01', 'Faculty of Engineering', 'ME', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('KRUPESH ANDHAK', 'krupeshandhak1991@yahoo.com', '2024-08-01', 'School of Computing', 'IS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('LEE YI JIA', 'leeyijia1989@gmail.com', '2021-08-01', 'Faculty of Science', 'Biology', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('SEAH WENG FAI', 'seahwengfai1990@yahoo.com', '2024-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('SHEN TIANYI', 'shentianyi1991@msn.com', '2023-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('WEN NA', 'wenna1990@msn.com', '2023-08-01', 'Faculty of Arts and Social Science', 'Economics', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('LIU LINXI', 'liulinxi1991@yahoo.com', '2023-08-01', 'Faculty of Arts and Social Science', 'Economics', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('DING WEI XIANG', 'dingweixiang1990@yahoo.com', '2024-08-01', 'School of Computing', 'IS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('CHEW SOEN NAM', 'chewsoennam1989@msn.com', '2024-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ZHANG YUZHAO', 'zhangyuzhao1990@gmail.com', '2023-08-01', 'Faculty of Arts and Social Science', 'Geography', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ZHENG NANA', 'zhengnana1991@gmail.com', '2024-08-01', 'Faculty of Arts and Social Science', 'Geography', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('NEHAL KANWAT', 'nehalkanwat1989@gmail.com', '2024-08-01', 'Faculty of Arts and Social Science', 'Language', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('NG YAN FEN', 'ngyanfen2010@msn.com', '2022-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('CHNG HUI LING', 'chnghuiling1992@gmail.com', '2023-08-01', 'Faculty of Arts and Social Science', 'History', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('TAN WEI SHENG', 'tanweisheng1989@gmail.com', '2024-08-01', 'Faculty of Arts and Social Science', 'Geography', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('LIEW LIEN LER', 'liewlienler2010@yahoo.com', '2024-08-01', 'Faculty of Engineering', 'CE', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('NGOO KAI TING', 'ngookaiting1991@yahoo.com', '2024-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ZHANG CONG', 'zhangcong2010@hotmail.com', '2024-08-01', 'Faculty of Engineering', 'EE', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('CHIA WEI GUO', 'chiaweiguo1990@hotmail.com', '2022-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('LIU YIYANG', 'liuyiyang1992@msn.com', '2024-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('LIU ZHENCAI', 'liuzhencai1990@msn.com', '2024-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('POH HUI LING', 'pohhuiling1992@hotmail.com', '2021-08-01', 'Faculty of Science', 'Biology', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('NG QI YANG', 'ngqiyang1989@msn.com', '2023-08-01', 'Faculty of Engineering', 'CE', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('NEELAM DEOL', 'neelamdeol2011@hotmail.com', '2022-08-01', 'Faculty of Arts and Social Science', 'Language', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('LI YUZHAO', 'liyuzhao1990@gmail.com', '2023-08-01', 'Faculty of Arts and Social Science', 'Economics', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('VARGHESE ANEJA', 'vargheseaneja1992@msn.com', '2024-08-01', 'School of Computing', 'IS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('QIN YIYANG', 'qinyiyang2010@hotmail.com', '2021-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ZHOU CONG', 'zhoucong1990@yahoo.com', '2024-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('TAY YONG MING', 'tayyongming1989@gmail.com', '2023-08-01', 'Faculty of Engineering', 'CE', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('SIOW CAO KHOA', 'siowcaokhoa1991@msn.com', '2024-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('TAN HUI LIN', 'tanhuilin1989@hotmail.com', '2021-08-01', 'School of Computing', 'IS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('KEN OWEN', 'kenowen2011@yahoo.com', '2021-08-01', 'Faculty of Arts and Social Science', 'Geography', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('HUANG XUANTI', 'huangxuanti1992@msn.com', '2021-08-01', 'School of Computing', 'IS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('LISA SMITH', 'lisasmith2011@msn.com', '2021-08-01', 'Faculty of Science', 'Chemistry', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('LIU JUN', 'liujun1989@msn.com', '2021-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('SUBRAMANIAM GHANTASALA', 'subramaniamghantasala2011@msn.com', '2021-08-01', 'School of Computing', 'IS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('JENNY HUNT', 'jennyhunt1991@gmail.com', '2022-08-01', 'Faculty of Arts and Social Science', 'Geography', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('SEAH TECK KEE', 'seahteckkee1990@gmail.com', '2022-08-01', 'Faculty of Arts and Social Science', 'Geography', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ZHOU XIALIN', 'zhouxialin1990@yahoo.com', '2022-08-01', 'Faculty of Arts and Social Science', 'Geography', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('JENNY BECKHAM', 'jennybeckham1992@gmail.com', '2022-08-01', 'Faculty of Arts and Social Science', 'Geography', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('IRIS BROWN', 'irisbrown1992@hotmail.com', '2022-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('CHOY JIAN MIN', 'choyjianmin1991@gmail.com', '2022-08-01', 'Faculty of Arts and Social Science', 'Geography', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ZHAO YANG', 'zhaoyang1989@yahoo.com', '2022-08-01', 'Faculty of Arts and Social Science', 'Geography', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('QIN YUWEI', 'qinyuwei2011@hotmail.com', '2023-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('DAVID HALL', 'davidhall1992@yahoo.com', '2023-08-01', 'Faculty of Arts and Social Science', 'Geography', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('GE DUO', 'geduo2010@yahoo.com', '2023-08-01', 'Faculty of Engineering', 'ME', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('NG YONG MING', 'ngyongming2011@yahoo.com', '2023-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('ANG JIA YI', 'angjiayi1990@hotmail.com', '2023-08-01', 'School of Computing', 'CS', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('SHEN WANTING', 'shenwanting2011@yahoo.com', '2023-08-01', 'Faculty of Engineering', 'CE', NULL);
INSERT INTO student (name, email, year, faculty, department, graduate) VALUES ('CHOY YI TING', 'choyyiting1992@hotmail.com', '2023-08-01', 'Faculty of Science', 'Biology', NULL);

